### ISSUE TITLE
Broken link in job listing

### ISSUE THREAD

**Issue by elimisteve** [dbt-labs/handbook#82]
Hi there!

Your job listing at https://boards.greenhouse.io/dbtlabsinc/jobs/4351839005 tries to link to your core values by linking to https://github.com/fishtown-analytics/corp/blob/master/values.md , but it looks like these values are now located at https://github.com/dbt-labs/handbook/blob/main/docs/values.md .

**Comment by leighstaub** [comment]
Hello! Thanks for letting us know. I think this is corrected in our job postings now -- please let us know if you see otherwise!
